const {app,BrowserWindow,nativeTheme,powerSaveBlocker}=require('electron');
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..'),out=path.join(root,'dist','verification');
fs.mkdirSync(out,{recursive:true});
process.env.WIDGET_SMOKE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'workday-v3-smoke-'));
app.setPath('userData',process.env.WIDGET_SMOKE_DIR);
fs.writeFileSync(path.join(process.env.WIDGET_SMOKE_DIR,'user-config.json'),JSON.stringify({schemaVersion:3,theme:'system',autoStart:false,enableKeepAwake:false,enableTelegramBot:false}));
require('../src/main');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const errors=[];
app.on('web-contents-created',(_,wc)=>{wc.on('console-message',(_,level,message)=>{if(level>=3)errors.push(message);});});
async function run(){
 await app.whenReady();await delay(2000);
 const main=BrowserWindow.getAllWindows()[0];
 const evaluate=code=>main.webContents.executeJavaScript(code);
 const capture=async(win,name)=>{await win.webContents.capturePage();await delay(700);fs.writeFileSync(path.join(out,name),(await win.webContents.capturePage()).toPNG());};
 assert(await evaluate("!!document.getElementById('aiCards')"),'Main document loaded');
 assert.equal(await evaluate("document.querySelectorAll('#stageStrip [data-stage]').length"),3,'Three countdown stages render');
 assert.equal(await evaluate("document.querySelectorAll('#stageStrip .active').length"),1,'One countdown stage is active');
 assert(await evaluate("['start','lunch','home'].includes(document.querySelector('#stageStrip .active').dataset.stage)"),'Active countdown stage is valid');
 const fixture={config:require('../src/core/config').normalizeConfig({schemaVersion:3,theme:'system',width:350,enableKeepAwake:false,showSpotify:true}),activeApps:{codex:true,antigravity:true,claude:true},dark:true,caffeine:{enabled:false},snapshot:{updatedAt:new Date().toISOString(),providers:{}}};
 for(const id of ['codex','claude','antigravity_gemini','antigravity_claude_gpt'])fixture.snapshot.providers[id]={status:'ok',metrics:{session:{remaining:52,resetAt:new Date(Date.now()+3600000).toISOString()},weekly:{remaining:88,resetAt:new Date(Date.now()+86400000).toISOString()}}};
 await evaluate("require('electron').ipcRenderer.emit('widget-state',null,"+JSON.stringify(fixture)+")");
 assert.equal(await evaluate("document.querySelectorAll('.ai-card').length"),3);
 await evaluate("require('electron').ipcRenderer.emit('spotify-update',null,{running:true,track:'Feel Special',artist:'TWICE',paused:false,position_sec:180,duration_sec:206,shuffleState:false,trackId:'1111111111111111111111'})");
 await delay(500);
 assert.equal(await evaluate("document.getElementById('spotifyTrack').textContent"),'Feel Special');
 await evaluate("require('electron').ipcRenderer.emit('spotify-auth-changed',null,{connected:true});document.getElementById('btnSpotifyShuffle').click()");
 assert.equal(await evaluate("document.getElementById('btnSpotifyShuffle').getAttribute('aria-pressed')"),'true');
 assert.equal(await evaluate("document.getElementById('btnSpotifyQueue').classList.contains('hidden')"),false);
 assert.equal(await evaluate("document.getElementById('btnSpotifyShuffle').classList.contains('active')"),true);
 await capture(main,'widget-dark.png');
 nativeTheme.themeSource='light';await evaluate("require('electron').ipcRenderer.emit('system-theme',null,false)");await delay(300);
 assert.equal(await evaluate("document.documentElement.dataset.theme"),'light');
 await capture(main,'widget-light.png');

 await evaluate("require('electron').ipcRenderer.emit('spotify-update',null,{running:true,track:'Feel Special',artist:'TWICE',paused:false,position_sec:186.2,duration_sec:206})");
 await delay(600);
 assert.equal(await evaluate("document.getElementById('spotifyRollcallName').textContent"),'Im Nayeon');
 const chantHeight=await evaluate("document.getElementById('spotifyBar').offsetHeight");
 await delay(800);
 await capture(main,'twice-chant-light.png');
 assert.equal(await evaluate("document.querySelectorAll('.chant-dots i').length"),9);
 assert(await evaluate("(()=>{const n=document.getElementById('spotifyRollcallName'),p=n.parentElement;return n.scrollWidth<=p.clientWidth})()"),'Member name fits narrow widget');
 nativeTheme.themeSource='dark';await delay(200);await capture(main,'twice-chant-dark.png');
 nativeTheme.themeSource='light';
 assert.equal(await evaluate("document.getElementById('spotifyBar').offsetHeight"),chantHeight,'Chant keeps stable height');

 await evaluate("window.dispatchEvent(new CustomEvent('music-settings',{detail:{showSpotify:true,artistThemes:true,fanEffects:false,reduceMotion:false}}))");
 assert.equal(await evaluate("document.getElementById('spotifyBar').classList.contains('feel-special-rollcall')"),false);
 assert.equal(await evaluate("document.getElementById('chantStage').hidden"),true);
 await evaluate("require('electron').ipcRenderer.emit('spotify-update',null,{running:true,track:'Test (SANA, JIHYO, TZUYU)',artist:'TWICE',paused:false,position_sec:0,duration_sec:200})");
 assert.equal(await evaluate("document.getElementById('spotifyArtist').textContent"),'Sana · 1 / 3');
 await delay(3300);
 assert.equal(await evaluate("document.getElementById('spotifyArtist').textContent"),'Jihyo · 2 / 3');
 assert(await evaluate("document.getElementById('spotifyBar').classList.contains('artist-jihyo')"));
 for(const artist of ['告五人','Accusefive']){
  await evaluate("require('electron').ipcRenderer.emit('spotify-update',null,"+JSON.stringify({running:true,track:'愛人錯過',artist,paused:false,position_sec:10,duration_sec:200})+")");
  assert(await evaluate("document.getElementById('spotifyBar').classList.contains('artist-ag5')"));
  await delay(700);
  assert.equal(await evaluate("getComputedStyle(document.getElementById('spotifyProgressFill')).backgroundColor"),'rgb(143, 227, 136)');
  assert.equal(await evaluate("document.getElementById('spotifyArtist').textContent"),artist);
 }
 assert.equal(await evaluate("document.querySelectorAll('.ai-card:not([hidden])').length"),1);
 const before=await evaluate("document.querySelector('.ai-card:not([hidden])').dataset.provider");
 await evaluate("document.getElementById('nextAI').click()");
 assert.notEqual(await evaluate("document.querySelector('.ai-card:not([hidden])').dataset.provider"),before);
 assert.equal(await evaluate("document.querySelectorAll('#carouselDots button').length"),3);
 await evaluate("require('electron').ipcRenderer.emit('spotify-update',null,{running:true,track:'Feel Special',artist:'TWICE',paused:true})");
 assert.equal(await evaluate("getComputedStyle(document.getElementById('spotifyBar')).display"),'none');
 await capture(main,'widget-carousel.png');
 assert(main.getBounds().height<=220,'Discreet widget height without music');
 await evaluate("Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});state.config.carouselSeconds=3;carouselHovered=false;lastCarouselChange=Date.now()");
 const selected=await evaluate("document.querySelector('.ai-card:not([hidden])').dataset.provider");
 await delay(4200);
 assert.notEqual(await evaluate("document.querySelector('.ai-card:not([hidden])').dataset.provider"),selected,'AI rotates automatically');
 await evaluate("document.getElementById('aiSection').dispatchEvent(new MouseEvent('mouseenter'))");
 const hovered=await evaluate("document.querySelector('.ai-card:not([hidden])').dataset.provider");
 await delay(4200);
 assert.equal(await evaluate("document.querySelector('.ai-card:not([hidden])').dataset.provider"),hovered,'Hover pauses rotation');
 await evaluate("delete document.hidden;document.getElementById('aiSection').dispatchEvent(new MouseEvent('mouseleave'))");
 fixture.config.layout='compact';
 await evaluate("require('electron').ipcRenderer.emit('widget-state',null,"+JSON.stringify(fixture)+")");
 assert.equal(await evaluate("getComputedStyle(document.getElementById('aiSection')).display"),'none');
 fixture.config.layout='standard';fixture.config.aiLayout='carousel';main.setSize(260,800);
 fixture.activeApps={claude:true};await evaluate("require('electron').ipcRenderer.emit('widget-state',null,"+JSON.stringify(fixture)+")");
 assert.equal(await evaluate("document.querySelectorAll('.ai-card').length"),1);
 fixture.activeApps={};await evaluate("require('electron').ipcRenderer.emit('widget-state',null,"+JSON.stringify(fixture)+")");
 assert.equal(await evaluate("document.getElementById('aiSection').hidden"),true);
 await evaluate("require('electron').ipcRenderer.send('open-settings')");await delay(1200);
 const settings=BrowserWindow.getAllWindows().find(w=>w!==main);
 assert(settings,'Independent settings window exists');
 await settings.webContents.executeJavaScript("document.querySelector('[data-tab=caffeine]').click()");
 await delay(300);await capture(settings,'settings-light.png');
 await settings.webContents.executeJavaScript("document.getElementById('enableKeepAwake').checked=true;document.getElementById('caffeineDuration').value='30';document.getElementById('settingsForm').requestSubmit()");
 await delay(500);
 const result=await evaluate("require('electron').ipcRenderer.invoke('get-state')");
 assert.equal(result.caffeine.active,true,'Real OS blocker active after save');
 assert.equal(result.config.enableKeepAwake,true);
 await evaluate("require('electron').ipcRenderer.send('toggle-caffeine')");await delay(200);
 assert.equal((await evaluate("require('electron').ipcRenderer.invoke('get-state')")).caffeine.active,false);

 await settings.webContents.executeJavaScript("document.querySelector('[data-tab=appearance]').click()");
 settings.setSize(600,650);await delay(300);
 assert(await settings.webContents.executeJavaScript("document.documentElement.scrollWidth<=innerWidth"),'Settings fit at minimum width');
 const uiText=await settings.webContents.executeJavaScript("document.getElementById('settingsNav').textContent");
 assert(!/[\u4e00-\u9fff]/.test(uiText),'Navigation is English');
 const {ipcMain}=require('electron');let requestedPlaylist=null;
 for(const channel of ['spotify-list-playlists','spotify-playlist-devices','spotify-play-playlist'])ipcMain.removeHandler(channel);
 ipcMain.handle('spotify-list-playlists',(_,offset)=>({ok:true,items:offset?[{id:'3333333333333333333333',name:'Evening',owner:'You',count:3}]:[{id:'1111111111111111111111',name:'TWICE favorites',owner:'You',count:20},{id:'2222222222222222222222',name:'Accusefive',owner:'You',count:10}],nextOffset:offset?null:50}));
 ipcMain.handle('spotify-playlist-devices',()=>({ok:true,items:[{id:'desktop',name:'This computer',active:true}]}));
 ipcMain.handle('spotify-play-playlist',(_,input)=>{requestedPlaylist=input;return {ok:true};});
 await evaluate("require('electron').ipcRenderer.emit('spotify-update',null,{running:true,track:'Test',artist:'Test',paused:false,position_sec:10,duration_sec:200})");await delay(500);
 await capture(main,'widget-before-more.png');
 const beforeMore=await evaluate("document.getElementById('shell').getBoundingClientRect().height");
 await evaluate("document.getElementById('btnSpotifyMore').click()");await delay(1000);
 assert.equal(await evaluate("document.getElementById('shell').getBoundingClientRect().height"),beforeMore,'More opens a separate window without growing widget');
 assert.equal(await evaluate("document.getElementById('spotifyPopover')"),null);

 const library=BrowserWindow.getAllWindows().find(w=>w!==main&&w!==settings);
 assert(library,'Music controls open separately');
 assert.deepEqual(library.getSize(),[800,730],'Music window uses Settings default size');
 await evaluate("document.getElementById('playlistButton').click()");await delay(100);
 assert.equal(BrowserWindow.getAllWindows().length,3,'Music note reuses the same window');

 const lib=code=>library.webContents.executeJavaScript(code);
 assert.equal(await lib("document.querySelectorAll('.playlist-item').length"),2);
 await lib("document.getElementById('more').click()");await delay(200);
 assert.equal(await lib("document.querySelectorAll('.playlist-item').length"),3);
 await lib("document.getElementById('filter').value='TWICE';document.getElementById('filter').dispatchEvent(new Event('input'));document.getElementById('device').value='desktop';document.querySelector('.playlist-item').click()");await delay(200);
 assert.deepEqual(requestedPlaylist,{id:'1111111111111111111111',deviceId:'desktop'});
 assert((await lib("document.getElementById('status').textContent")).startsWith('Playback requested:'));
 await capture(library,'spotify-playlists.png');
 let likedRequest=null,artistRequest=null;
 for(const channel of ['spotify-liked-songs','spotify-search-liked','spotify-search-artists','spotify-play-artist','spotify-play-liked'])ipcMain.removeHandler(channel);
 ipcMain.handle('spotify-liked-songs',(_,offset)=>({ok:true,items:[{id:offset?'2222222222222222222222':'1111111111111111111111',name:offset?'Second page song':'My liked song',owner:'TWICE',count:null}],nextOffset:offset?null:50,total:51}));
 ipcMain.handle('spotify-search-liked',(_,query)=>({ok:true,items:[{id:'4444444444444444444444',name:'Found beyond page one',owner:query,count:null}],scanned:101,cached:false}));
 ipcMain.handle('spotify-search-artists',(_,input)=>({ok:true,items:[{id:'3333333333333333333333',name:input.query,owner:'Artist',count:null}],nextOffset:null}));
 ipcMain.removeHandler('spotify-add-track-queue');let queuedTrack=null;
 ipcMain.handle('spotify-add-track-queue',(_,input)=>{queuedTrack=input;return {ok:true};});
 ipcMain.handle('spotify-play-liked',(_,input)=>{likedRequest=input;return {ok:true};});
 ipcMain.handle('spotify-play-artist',(_,input)=>{artistRequest=input;return {ok:true};});
 await lib("document.querySelector('[data-view=liked]').click()");await delay(200);
 await lib("document.getElementById('playPage').click()");await delay(200);
 assert.deepEqual(likedRequest.ids,['1111111111111111111111']);
 await lib("document.querySelector('.queue-track').click()");await delay(200);
 assert.deepEqual(queuedTrack,{id:'1111111111111111111111',deviceId:'desktop'});
 assert((await lib("document.getElementById('status').textContent")).startsWith('Added to queue:'));
 await lib("document.getElementById('more').click()");await delay(200);
 assert.equal(await lib("document.querySelector('.playlist-item strong').textContent"),'Second page song');
 await lib("document.getElementById('previousPage').click()");await delay(200);
 assert.equal(await lib("document.querySelector('.playlist-item strong').textContent"),'My liked song');
 await lib("document.getElementById('filter').value='far away';document.getElementById('searchLibrary').click()");await delay(200);
 assert.equal(await lib("document.querySelector('.playlist-item strong').textContent"),'Found beyond page one');
 assert((await lib("document.getElementById('status').textContent")).includes('across 101'));
 await capture(library,'spotify-liked-songs.png');
 await lib("document.querySelector('[data-view=artists]').click();document.getElementById('filter').value='Accusefive';document.getElementById('searchLibrary').click()");await delay(200);
 await lib("document.querySelector('.playlist-item').click()");await delay(200);
 assert.equal(artistRequest.id,'3333333333333333333333');assert.equal(artistRequest.deviceId,'desktop');
 await capture(library,'spotify-artists.png');

 assert(await lib("document.documentElement.scrollWidth<=innerWidth"));
 assert.equal(errors.length,0,errors.join('\n'));

 fs.writeFileSync(path.join(out,'smoke.json'),JSON.stringify({passed:true,checks:['three AI cards','single/no AI visibility','system light theme','Spotify/TWICE content','settings window','settings save','real OS Caffeine start/stop','TWICE timed roll call','fan effects off','single visible AI with manual carousel navigation','automatic rotation and hover pause','Spotify hidden when paused','height under 220px','compact layout','English settings at minimum width'],rendererErrors:errors},null,2));
 app.quit();
}
run().catch(e=>{fs.writeFileSync(path.join(out,'smoke-error.txt'),e.stack+'\n'+errors.join('\n'));console.error(e);app.exit(1);});
